{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Neptune Tutorial"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "https://app.neptune.ai/emmachancellor/Longitudinal-IBD/e/LON-4\n",
      "Remember to stop your run once you’ve finished logging your metadata (https://docs.neptune.ai/api/run#stop). It will be stopped automatically only when the notebook kernel/interactive console is terminated.\n"
     ]
    }
   ],
   "source": [
    "import neptune.new as neptune\n",
    "run = neptune.init_run(project='emmachancellor/Longitudinal-IBD', \n",
    "                       api_token='eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiI3OWY4NTFhMC1hYmY1LTQ0NDQtOWE4ZS0zMDVhOGJlMjgyMTcifQ==')\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Logging Hyperparameters\n",
    "run[\"algorithm\"] = \"ConvNet\" #this creates a field named 'algorithm' and assigns the string 'ConvNet' to it\n",
    "\n",
    "# Create a field of the appropriate type for each dictionary entry:\n",
    "params = {\n",
    "    \"activation\": \"sigmoid\",\n",
    "    \"dropout\": 0.25,\n",
    "    \"learning_rate\": 0.1,\n",
    "    \"n_epochs\": 100,\n",
    "}\n",
    "\n",
    "run[\"model/parameters\"] = params\n",
    "# Because of how the structure is specified ('model/parameters') the parameter fields \n",
    "# are stored in the 'parameters' namespace, nested under the 'model' namespace\n",
    "\n",
    "\n",
    "# Oops, what if I want to change an existing value?\n",
    "run[\"model/parameters/activation\"] = \"ReLU\"\n",
    "\n",
    "# Or add a new field: \n",
    "run[\"model/parameters/batch_size\"] = 64"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Log Metrics\n",
    "\n",
    "# Each log() call adds a new value to the series, so it's designed to be used in a loop\n",
    "for epoch in range(params[\"n_epochs\"]):\n",
    "    # this would normally be your training loop\n",
    "    run[\"train/loss\"].log(0.99**epoch)\n",
    "    run[\"train/acc\"].log(1.01**epoch)\n",
    "    run[\"eval/loss\"].log(0.98**epoch)\n",
    "    run[\"eval/acc\"].log(1.02**epoch)\n",
    "# This creates the namespaces 'train' and 'eval', each with a 'loss' and 'acc' field"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Track a data file\n",
    "\n",
    "# track_files() allows you to log metadata about any dataset, model, or other artifact stored in a file\n",
    "run[\"data_versions/train\"].track_files(\"sample.csv\")\n",
    "\n",
    "# This records metadata about the CSV file in the 'data_versions/train' field, which helps identify\n",
    "# the exact version of the file that was used for this run "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Upload a file\n",
    "\n",
    "# If you want to upload the file in full to neptune then use:\n",
    "run[\"data_sample\"].upload(\"sample.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Stop the run\n",
    "\n",
    "# Record some value/finish analysis:\n",
    "run[\"f1_score\"] = 0.95\n",
    "\n",
    "# Now that we are finished logging, we can stop the run method\n",
    "run.stop()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "https://app.neptune.ai/emmachancellor/Longitudinal-IBD/e/LON-5\n",
      "Remember to stop your run once you’ve finished logging your metadata (https://docs.neptune.ai/api/run#stop). It will be stopped automatically only when the notebook kernel/interactive console is terminated.\n"
     ]
    }
   ],
   "source": [
    "# Full Script\n",
    "import neptune.new as neptune\n",
    "\n",
    "run = neptune.init_run(project='emmachancellor/Longitudinal-IBD', \n",
    "                       api_token='eyJhcGlfYWRkcmVzcyI6Imh0dHBzOi8vYXBwLm5lcHR1bmUuYWkiLCJhcGlfdXJsIjoiaHR0cHM6Ly9hcHAubmVwdHVuZS5haSIsImFwaV9rZXkiOiI3OWY4NTFhMC1hYmY1LTQ0NDQtOWE4ZS0zMDVhOGJlMjgyMTcifQ==')\n",
    "\n",
    "\n",
    "run[\"algorithm\"] = \"ConvNet\"\n",
    "\n",
    "params = {\n",
    "    \"activation\": \"sigmoid\",\n",
    "    \"dropout\": 0.25,\n",
    "    \"learning_rate\": 0.1,\n",
    "    \"n_epochs\": 100,\n",
    "}\n",
    "run[\"model/parameters\"] = params\n",
    "\n",
    "run[\"model/parameters/activation\"] = \"ReLU\"\n",
    "run[\"model/parameters/batch_size\"] = 32\n",
    "\n",
    "for epoch in range(params[\"n_epochs\"]):\n",
    "    # this would normally be your training loop\n",
    "    run[\"train/loss\"].log(0.99**epoch)\n",
    "    run[\"train/acc\"].log(1.01**epoch)\n",
    "    run[\"eval/loss\"].log(0.98**epoch)\n",
    "    run[\"eval/acc\"].log(1.02**epoch)\n",
    "\n",
    "run[\"data_versions/train\"].track_files(\"sample.csv\")\n",
    "run[\"data_sample\"].upload(\"sample.csv\")\n",
    "\n",
    "run[\"f1_score\"] = 0.95\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Shutting down background jobs, please wait a moment...\n",
      "Done!\n",
      "Waiting for the remaining 1 operations to synchronize with Neptune. Do not kill this process.\n",
      "All 1 operations synced, thanks for waiting!\n",
      "Explore the metadata in the Neptune app:\n",
      "https://app.neptune.ai/emmachancellor/Longitudinal-IBD/e/LON-5\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Experiencing connection interruptions. Will try to reestablish communication with Neptune. Internal exception was: RequestsFutureAdapterConnectionError\n",
      "Communication with Neptune restored!\n",
      "Experiencing connection interruptions. Will try to reestablish communication with Neptune. Internal exception was: RequestsFutureAdapterConnectionError\n",
      "Experiencing connection interruptions. Will try to reestablish communication with Neptune. Internal exception was: RequestsFutureAdapterConnectionError\n",
      "Experiencing connection interruptions. Will try to reestablish communication with Neptune. Internal exception was: RequestsFutureAdapterConnectionError\n",
      "Experiencing connection interruptions. Will try to reestablish communication with Neptune. Internal exception was: RequestsFutureAdapterConnectionError\n",
      "Experiencing connection interruptions. Will try to reestablish communication with Neptune. Internal exception was: RequestsFutureAdapterConnectionError\n",
      "Experiencing connection interruptions. Will try to reestablish communication with Neptune. Internal exception was: RequestsFutureAdapterTimeout\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n",
      "Experiencing connection interruptions. Reestablishing communication with Neptune.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected error occurred in Neptune background thread: Killing Neptune asynchronous thread. All data is safe on disk and can be later synced manually using `neptune sync` command.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread NeptuneAsyncOpProcessor:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/operation_processors/async_operation_processor.py\", line 230, in run\n",
      "    super().run()\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/threading/daemon.py\", line 51, in run\n",
      "    self.work()\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/operation_processors/async_operation_processor.py\", line 246, in work\n",
      "    self.process_batch(batch, version)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/threading/daemon.py\", line 75, in wrapper\n",
      "    result = func(self_, *args, **kwargs)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/operation_processors/async_operation_processor.py\", line 262, in process_batch\n",
      "    operations=batch,\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/backends/hosted_neptune_backend.py\", line 481, in execute_operations\n",
      "    operations=itertools.chain(assign_artifact_operations, preprocessed_operations.other_operations),\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/backends/utils.py\", line 111, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/backends/hosted_neptune_backend.py\", line 632, in _execute_operations\n",
      "    result = self.leaderboard_client.api.executeOperations(**kwargs).response().result\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/backends/swagger_client_wrapper.py\", line 86, in __call__\n",
      "    future = self._api_method(*args, **kwargs)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/bravado/client.py\", line 279, in __call__\n",
      "    request_config=request_config,\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/bravado/requests_client.py\", line 399, in request\n",
      "    self.authenticated_request(sanitized_params),\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/bravado/requests_client.py\", line 440, in authenticated_request\n",
      "    return self.apply_authentication(requests.Request(**request_params))\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/bravado/requests_client.py\", line 445, in apply_authentication\n",
      "    return self.authenticator.apply(request)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/common/oauth.py\", line 132, in apply\n",
      "    self.auth.refresh_token_if_needed()\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/common/utils.py\", line 318, in wrapper\n",
      "    raise ConnectionLost()\n",
      "neptune.legacy.api_exceptions.ConnectionLost: Connection lost. Please try again.\n",
      "\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected error occurred in Neptune background thread: Killing Neptune ping thread. Your run's status will not be updated and the run will be shown as inactive.\n",
      "Unexpected error occurred in Neptune background thread: Killing Neptune asynchronous thread. All data is safe on disk and can be later synced manually using `neptune sync` command.\n",
      "Unexpected error occurred in Neptune background thread: Killing Neptune ping thread. Your run's status will not be updated and the run will be shown as inactive.\n",
      "Unexpected error occurred in Neptune background thread: Killing Neptune asynchronous thread. All data is safe on disk and can be later synced manually using `neptune sync` command.\n",
      "Unexpected error occurred in Neptune background thread: Killing Neptune ping thread. Your run's status will not be updated and the run will be shown as inactive.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception in thread NeptunePing:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/threading/daemon.py\", line 51, in run\n",
      "    self.work()\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/threading/daemon.py\", line 75, in wrapper\n",
      "    result = func(self_, *args, **kwargs)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/utils/ping_background_job.py\", line 65, in work\n",
      "    self._container.ping()\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/metadata_containers/metadata_container.py\", line 205, in ping\n",
      "    self._backend.ping(self._id, self.container_type)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/backends/utils.py\", line 111, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/backends/hosted_neptune_backend.py\", line 433, in ping\n",
      "    **request_kwargs,\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/backends/swagger_client_wrapper.py\", line 86, in __call__\n",
      "    future = self._api_method(*args, **kwargs)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/bravado/client.py\", line 279, in __call__\n",
      "    request_config=request_config,\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/bravado/requests_client.py\", line 399, in request\n",
      "    self.authenticated_request(sanitized_params),\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/bravado/requests_client.py\", line 440, in authenticated_request\n",
      "    return self.apply_authentication(requests.Request(**request_params))\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/bravado/requests_client.py\", line 445, in apply_authentication\n",
      "    return self.authenticator.apply(request)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/common/oauth.py\", line 132, in apply\n",
      "    self.auth.refresh_token_if_needed()\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/common/utils.py\", line 318, in wrapper\n",
      "    raise ConnectionLost()\n",
      "neptune.legacy.api_exceptions.ConnectionLost: Connection lost. Please try again.\n",
      "\n",
      "Exception in thread NeptuneAsyncOpProcessor:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/operation_processors/async_operation_processor.py\", line 230, in run\n",
      "    super().run()\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/threading/daemon.py\", line 51, in run\n",
      "    self.work()\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/operation_processors/async_operation_processor.py\", line 246, in work\n",
      "    self.process_batch(batch, version)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/threading/daemon.py\", line 75, in wrapper\n",
      "    result = func(self_, *args, **kwargs)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/operation_processors/async_operation_processor.py\", line 262, in process_batch\n",
      "    operations=batch,\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/backends/hosted_neptune_backend.py\", line 481, in execute_operations\n",
      "    operations=itertools.chain(assign_artifact_operations, preprocessed_operations.other_operations),\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/backends/utils.py\", line 111, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/backends/hosted_neptune_backend.py\", line 632, in _execute_operations\n",
      "    result = self.leaderboard_client.api.executeOperations(**kwargs).response().result\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/backends/swagger_client_wrapper.py\", line 86, in __call__\n",
      "    future = self._api_method(*args, **kwargs)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/bravado/client.py\", line 279, in __call__\n",
      "    request_config=request_config,\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/bravado/requests_client.py\", line 399, in request\n",
      "    self.authenticated_request(sanitized_params),\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/bravado/requests_client.py\", line 440, in authenticated_request\n",
      "    return self.apply_authentication(requests.Request(**request_params))\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/bravado/requests_client.py\", line 445, in apply_authentication\n",
      "    return self.authenticator.apply(request)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/common/oauth.py\", line 132, in apply\n",
      "    self.auth.refresh_token_if_needed()\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/common/utils.py\", line 318, in wrapper\n",
      "    raise ConnectionLost()\n",
      "neptune.legacy.api_exceptions.ConnectionLost: Connection lost. Please try again.\n",
      "\n",
      "Exception in thread NeptunePing:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/threading/daemon.py\", line 51, in run\n",
      "    self.work()\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/threading/daemon.py\", line 75, in wrapper\n",
      "    result = func(self_, *args, **kwargs)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/utils/ping_background_job.py\", line 65, in work\n",
      "    self._container.ping()\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/metadata_containers/metadata_container.py\", line 205, in ping\n",
      "    self._backend.ping(self._id, self.container_type)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/backends/utils.py\", line 111, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/backends/hosted_neptune_backend.py\", line 433, in ping\n",
      "    **request_kwargs,\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/backends/swagger_client_wrapper.py\", line 86, in __call__\n",
      "    future = self._api_method(*args, **kwargs)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/bravado/client.py\", line 279, in __call__\n",
      "    request_config=request_config,\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/bravado/requests_client.py\", line 399, in request\n",
      "    self.authenticated_request(sanitized_params),\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/bravado/requests_client.py\", line 440, in authenticated_request\n",
      "    return self.apply_authentication(requests.Request(**request_params))\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/bravado/requests_client.py\", line 445, in apply_authentication\n",
      "    return self.authenticator.apply(request)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/common/oauth.py\", line 132, in apply\n",
      "    self.auth.refresh_token_if_needed()\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/common/utils.py\", line 318, in wrapper\n",
      "    raise ConnectionLost()\n",
      "neptune.legacy.api_exceptions.ConnectionLost: Connection lost. Please try again.\n",
      "\n",
      "Exception in thread NeptuneAsyncOpProcessor:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/operation_processors/async_operation_processor.py\", line 230, in run\n",
      "    super().run()\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/threading/daemon.py\", line 51, in run\n",
      "    self.work()\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/operation_processors/async_operation_processor.py\", line 246, in work\n",
      "    self.process_batch(batch, version)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/threading/daemon.py\", line 75, in wrapper\n",
      "    result = func(self_, *args, **kwargs)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/operation_processors/async_operation_processor.py\", line 262, in process_batch\n",
      "    operations=batch,\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/backends/hosted_neptune_backend.py\", line 481, in execute_operations\n",
      "    operations=itertools.chain(assign_artifact_operations, preprocessed_operations.other_operations),\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/backends/utils.py\", line 111, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/backends/hosted_neptune_backend.py\", line 632, in _execute_operations\n",
      "    result = self.leaderboard_client.api.executeOperations(**kwargs).response().result\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/backends/swagger_client_wrapper.py\", line 86, in __call__\n",
      "    future = self._api_method(*args, **kwargs)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/bravado/client.py\", line 279, in __call__\n",
      "    request_config=request_config,\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/bravado/requests_client.py\", line 399, in request\n",
      "    self.authenticated_request(sanitized_params),\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/bravado/requests_client.py\", line 440, in authenticated_request\n",
      "    return self.apply_authentication(requests.Request(**request_params))\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/bravado/requests_client.py\", line 445, in apply_authentication\n",
      "    return self.authenticator.apply(request)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/common/oauth.py\", line 132, in apply\n",
      "    self.auth.refresh_token_if_needed()\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/common/utils.py\", line 318, in wrapper\n",
      "    raise ConnectionLost()\n",
      "neptune.legacy.api_exceptions.ConnectionLost: Connection lost. Please try again.\n",
      "\n",
      "Exception in thread NeptunePing:\n",
      "Traceback (most recent call last):\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/threading.py\", line 926, in _bootstrap_inner\n",
      "    self.run()\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/threading/daemon.py\", line 51, in run\n",
      "    self.work()\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/threading/daemon.py\", line 75, in wrapper\n",
      "    result = func(self_, *args, **kwargs)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/utils/ping_background_job.py\", line 65, in work\n",
      "    self._container.ping()\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/metadata_containers/metadata_container.py\", line 205, in ping\n",
      "    self._backend.ping(self._id, self.container_type)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/backends/utils.py\", line 111, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/backends/hosted_neptune_backend.py\", line 433, in ping\n",
      "    **request_kwargs,\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/new/internal/backends/swagger_client_wrapper.py\", line 86, in __call__\n",
      "    future = self._api_method(*args, **kwargs)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/bravado/client.py\", line 279, in __call__\n",
      "    request_config=request_config,\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/bravado/requests_client.py\", line 399, in request\n",
      "    self.authenticated_request(sanitized_params),\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/bravado/requests_client.py\", line 440, in authenticated_request\n",
      "    return self.apply_authentication(requests.Request(**request_params))\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/bravado/requests_client.py\", line 445, in apply_authentication\n",
      "    return self.authenticator.apply(request)\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/common/oauth.py\", line 132, in apply\n",
      "    self.auth.refresh_token_if_needed()\n",
      "  File \"/Users/emmadyer/miniconda3/envs/py37/lib/python3.7/site-packages/neptune/common/utils.py\", line 318, in wrapper\n",
      "    raise ConnectionLost()\n",
      "neptune.legacy.api_exceptions.ConnectionLost: Connection lost. Please try again.\n",
      "\n"
     ]
    }
   ],
   "source": [
    "run.stop()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3.7.9 ('py37')",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.9"
  },
  "orig_nbformat": 4,
  "vscode": {
   "interpreter": {
    "hash": "723a964bb0aead0851d78ae64d6de99bdaf4f3c4f305be36213c7c02e14cf2bc"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
